spring:
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: ${PORT:8989}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#关闭弹出的默认认证登录框
security:
  basic:
    enabled: false
#对当前服务的重试次数
ribbon:
  MaxAutoRetries: 2
#切换相同Server的次数
  MaxAutoRetriesNextServer: 0
zuul:
#是否开启重试功能
  retryable: true
  routes:
#显式声明路由配置
    teacher:
      path: /teacher/**
      service-id: teacher-web
#反向代理,url路由的这种方式不支持负载均衡
    baidu:
      path: /baidu/**
      url: http://www.baidu.com
#设置敏感头部信息。 Cookie/Set-Cookie,增加代理的header，防止session丢失
#      sensitiveHeaders: Authorization

